/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.14.3/samples
 */
plugins {
    java
    application
}
repositories {
    mavenCentral()
}

application {
    mainClass = "snakegame.Main"
    applicationName = "snakegame-java"
}

// tasks.register<Jar>("jar") {
//     archiveBaseName.set("snakegame-java")
//     from(sourceSets.main.get().output)
//     manifest {
//         attributes["Main-Class"] = "snakegame.Main"
//     }
// }
